[package]
name = "boopbot"
version = "0.1.0"
authors = ["Barnabás Rátki <barna.ratki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"